export {AdmineditComponent} from './adminka/adminedit/adminedit.component';
export {AdminsideComponent} from './adminka/adminside/adminside.component';
export {AdmincoverComponent} from './adminka/admincover/admincover.component';
export {HomeComponent} from './home/home.component';
export {LoginComponent} from './login/login.component';
export {RegistComponent} from './regist/regist.component';
export {Page1Component} from './page1/page1.component';
export {Page2Component} from './page2/page2.component';
export {Page3Component} from './page3/page3.component';
